import { Timestamp } from "firebase-admin/firestore";

/**
 * Represents a meeting entity stored in Firestore.
 * 
 * @typedef {Object} Meeting
 * @property {string} [id] - The unique identifier of the meeting (generated by Firestore).
 * @property {string} title - The title or name of the meeting.
 * @property {string} userId - The ID of the user who owns or created the meeting.
 * @property {Timestamp} [createdAt] - Timestamp when the meeting was created.
 * @property {Timestamp} [updatedAt] - Timestamp when the meeting was last updated.
 */
export interface Meeting {
    id?: string;
    title: string;
    userId: string;
    createdAt?: Timestamp;
    updatedAt?: Timestamp;
}

/**
 * DTO used when creating a new meeting.
 * Excludes fields automatically generated by Firestore such as `id`, `createdAt`, and `updatedAt`.
 * 
 * @typedef {Object} MeetingCreate
 * @property {string} title - The title of the meeting.
 * @property {string} userId - The ID of the user creating the meeting.
 */
export type MeetingCreate = Omit<Meeting, "id" | "createdAt" | "updatedAt">;

/**
 * DTO used when updating an existing meeting.
 * Only allows updating editable properties.
 * 
 * @typedef {Object} MeetingUpdate
 * @property {string} [title] - The new title of the meeting.
 * @property {Timestamp} [updatedAt] - Will be set automatically when updating.
 */
export type MeetingUpdate = Partial<Omit<Meeting, "id" | "userId" | "createdAt">>;
